title: pointR
logo: /assets/img/256x256.png
description: An R based IDE to generate SVG 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
release_mac: https://github.com/mslegrand/pointR/releases/download/v.0.4.6/ptr-0.4.6.dmg
release_linux: https://github.com/mslegrand/pointR/releases/download/v.0.4.6/ptr_0.4.6_amd64.deb
release_win: https://github.com/mslegrand/pointR/releases/download/v.0.4.6/ptr.Setup.0.4.6.exe
release_current: Hilbert v.0.4.6
